# Back-up config
env:
  WINIT_X11_SCALE_FACTOR: "1.0"

window:
  padding:
    x: 4
    y: 4

font:
  normal:
    family: Iosevka Nerd Font
    style: Regular

  bold:
    family: Iosevka Nerd Font
    style: Bold

  italic:
    family: Iosevka Nerd Font
    style: Italic

  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic

  size: 12

key_bindings:
  - { key: "N", mods: Control|Shift, action: SpawnNewInstance }
