set clipboard+=unnamedplus
set colorcolumn=80
set completeopt=menuone,noselect
set cursorline
set expandtab
set foldmethod=syntax
set ignorecase
set nofoldenable
set noswapfile
set nowrap
set number
set relativenumber
set scrolloff=12
set shiftwidth=2
set signcolumn=yes
set smartindent
set splitbelow
set splitright
set tabstop=2 softtabstop=2
set termguicolors
set undofile
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.svg,*.png,*.jpg,*.gif,node_modules
