# Inserts a blank line between shell prompts
add_newline = false

# The name of the module we are configuring is "character"
[character]
# Replace the "❯" symbol in the prompt with "➜"
success_symbol = "[➜](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

